spring:
    # SPRING PROFILES
    data:
      elasticsearch:
        cluster-name: you_es_cluster
        cluster-nodes: 192.168.33.102:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
        properties:
          path:
            logs: ./elasticsearch/log #elasticsearch日志存储目录
            data: ./elasticsearch/data #elasticsearch数据存储目录
mybatis:
  mapper-locations: classpath:mapper/*.xml

druid:
  url: jdbc:mysql://rm-wz9xa7a8307pmzhr4.mysql.rds.aliyuncs.com:3306/szqb_pro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  username: szqb_read
  password: szqb@2018


# LOGGING
server:
  port: 28033
  servlet:
    context-path: /elsearch
# 日志
logging:
    config: classpath:logback.xml

