elasticsearch:
  ip: 127.0.0.1:9200
# SPRING PROFILES
mybatis:
  mapper-locations: classpath:mapper/*.xml

druid:
  url: jdbc:mysql://154.211.159.68:4006/ims?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  username: qpread58
  password: "hsk6$#5#$%"


# LOGGING
server:
  port: 8033
  servlet:
    context-path: /elsearch
# 日志
logging:
    config: classpath:logback.xml

